apiVersion: certmanager.k8s.io/v1alpha1
kind: ClusterIssuer
metadata:
  name: letsencript-prod
spec:
  acme:
    server: https://acmev02.api.letsencrypt.org/directory
    email: 'ladis29@gmail.com'
    privateKeySecretRef:
      name: letsencript-prod
    http01: {}